# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd489900047d074960492caf7cd82a6e2d6e44378fbe63d73910d03de3a87fcdcd8f5455e2b365fe7262a65b962f4f35d983eee04fd2a918e66f5d2e051615b

test:
  secret_key_base: b100d62570e4c3da3e0dcf7585e66fc056e39a88ec43d63b2849f85ffb4c8e6151d27f18abd97ac435707d750afcbb20beb44b5671fbc4472ab371f0b5f24326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

all:
  OAUTH_CLIENT_ID: <%= ENV["OAUTH_CLIENT_ID"] %>
  OAUTH_CLIENT_SECRET: <%= ENV["OAUTH_CLIENT_SECRET"] %>
  APPLICATION_CONFIG_SECRET_TOKEN: <%= ENV["APPLICATION_CONFIG_SECRET_TOKEN"] %>
